Repository bagaluten/metio-rs, pull requests merged in 2023-11, with the labels that each got.

#11 WIP: feature(client): Add client module with reference implementation
  Cargo.toml
  src/client/mod.rs
  src/client/sqlite/mod.rs
  src/lib.rs
  src/types/mod.rs
Labels: feature, minor

#13 replaces existing test data if created twice
  src/client/sqlite/mod.rs
Labels: feature

#15 add test
  src/types/mod.rs
Labels: chore

#16 feat(types): Add more tests
  Cargo.toml
  src/client/mod.rs
  src/client/sqlite/mod.rs
  src/types/mod.rs
Labels: feature

#18 fix(client/sqlite): Implement clone and debug
  src/client/sqlite/mod.rs
Labels: patch
